# Generated by Django 2.0.3 on 2018-06-01 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('genere', models.CharField(max_length=100)),
                ('album_logo', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist', models.CharField(max_length=30)),
                ('wrapperType', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
                ('artistName', models.CharField(max_length=200)),
                ('trackName', models.CharField(max_length=200)),
                ('releaseDate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('song_title', models.CharField(max_length=1000)),
                ('is_favourite', models.BooleanField(default=False)),
                ('source', models.CharField(default='iTune', max_length=200)),
                ('song_logo', models.CharField(default='no logo', max_length=300)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicStore.Album')),
            ],
        ),
    ]
