# Generated by Django 2.0.3 on 2018-06-01 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured_artist',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='production_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
