# Generated by Django 2.0.3 on 2018-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0003_auto_20180601_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='production_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
