# Generated by Django 2.0.3 on 2018-06-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0006_auto_20180604_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='name',
        ),
    ]
