# Generated by Django 2.0.3 on 2018-11-08 09:55

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicStore', '0009_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('speaker', models.CharField(max_length=100)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=300)),
                ('youtube_link', models.URLField(max_length=300, unique=True, verbose_name='Youtube Video')),
            ],
        ),
    ]
